Moseph
TFSSplitDecision/InsideJob pull request #35
Opened 2024-01-18 20:30 UTC by Moseph90

Add the script to the main camera, all of the values for the camera position and rotation are available in the inpector. Make sure to add the player object to the player object slot in the inspector. It can be a little bit of a pain to try to get it just right, so please let me know when the main level is complete and I will come in and set up the parameters. Right now it's set up nicely for the test scene as proof of concept.

2024-01-18 22:56 UTC, cothon01 requested changes
Accidentally included another Unity project ("Inside Job" folder).

2024-01-19 16:51 UTC, Helcostr requested changes
Unity-ception. Please fix.

2024-01-19 18:33 UTC, Moseph90 commented
I moved all the folders in the new commit

2024-01-19 18:33 UTC, Helcostr commented
File count looks more resonable now. used to be 5k... now it's 27.

2024-01-19 18:58 UTC, cothon01 approved these changes
All good 👍

2024-01-20 02:44 UTC, Sneakydeaky approved these changes
Everything works good! if you had a sec id like to look over the code with you so I can learn about it!

2024-01-20 14:02 UTC, Helcostr approved these changes
Didn't check. two reviewers checked and so am clearing my request for change.

2024-01-20 18:41 UTC, merged